### ISSUE TITLE
ERR_IPC_CHANNEL_CLOSED running headless tests using cypress 14

### ISSUE THREAD

**Issue by kubmir** [reportportal/agent-js-cypress#213]
Hello,

I tried to set-up `@reportportal/agent-js-cypress` for Cypress 14.0.0 without any success. When I run test command for multiple specs, it fails after successful test run of the first spec file which is correctly reported to API.

I use quite simple config:

```
  reporter: '@reportportal/agent-js-cypress',
  reporterOptions: {
    apiKey: '<API_KEY>',
    endpoint: 'http://localhost:8080/api/v1',
    project: 'default_personal',
    launch: 'test_launch'
  },
```

`registerReportPortalPlugin` is called inside `setupNodeEvents` by call `registerReportPortalPlugin(on, config)`.

Report portal commands are registered and work well.

The error description is:
```
Channel closed
Error [ERR_IPC_CHANNEL_CLOSED]: Channel closed
at new NodeError (node:internal/errors:405:5)
at ChildProcess.send (node:internal/child_process:740:16)
at Server.configListener ...
```

I tried it with both Node 18 and Node 20, but the issue persists in both versions. Has anyone else encountered this issue and found a solution?

Thank you

**Comment by AmsterGet** [comment]
Hello @kubmir !
So after completing your the first spec, your entire run failed?
Have you tried to reproduce this problem for Cypress 13?

**Comment by kubmir** [comment]
Hello @AmsterGet, yes I tried it also with Cypress 13.17.0 and it caused the same issue.

The first spec file is successfully executed and data are visible in the ReportPortal. However, second spec file is not executed as whole cypress job fails with issue mentioned above.

**Comment by AmsterGet** [comment]
Hello @kubmir !
I've just released the new version of the agent with additional option [`debugIpc`](https://github.com/reportportal/agent-js-cypress/releases/tag/v5.5.0#:~:text=Added-,debugIpc,-option.%20Allows%20printing) that can be useful for debugging ipc connection issues.
Could you please run your tests again with this option enabled and share the logs with us?

**Comment by AmsterGet** [comment]
@kubmir just want to clarify - what is your setup for such broken executions?
OS type/version, any tools used to run the tests, etc.

**Comment by kubmir** [comment]
I tried this again with Cypress 15.3.0 and version 5.5.1 of `agent-js-cypress` and the issue still persists.

**Comment by super-tt-one** [comment]
We have/had exactly the same issue like @kubmir and we even exchanged few message about the details. I also went through many versions of cypress, agent-js-cypress, node and even tried to debug our gitlab runner containers and tested base images with different linux distros, but nothing helped. We could do the same test run tens of times successfully and then have 4-6 failed test runs in independent cicd pipelines. Since we run same test runs in both Jenkins and Gitlab and only had issues with Gitlab, we thought that issue was indeed with the gitlab runner we completely overlooked two things: even tough the runs ends with the IPC error, the agent was able to send results of the first spec and cypress returns error that no cypress results are found. 

After some heavy digging we noticed this might be a timing issue with the agent's initialization and running/finishing the first spec. With all the debug logging enabled, we were able to see that the config event happens after the first spec was finished. We cannot say for sure, but it looks like the agent isn't fully configured before it receives the first after spec/run event and crashes since it cannot handle the situation. Since slowing down tests artificially was not an option, we lowered "retryIpcInterval" default 1500ms to 400ms. With brute force testing we couldn't repeat the IPC error anymore and so far we have had four days without any IPC error incidents after running the first spec of the run.

I hope this helps others with the same problem and gives some hints how to be able to repeat and possibly even fix the issue.
