### ISSUE TITLE
ECONNREFUSED with reporter only when using cypress-multi-reporters

### ISSUE THREAD

**Issue by mleonard0826** [reportportal/agent-js-cypress#59]
Working off of agent-js-cypress 1.1.3, I see that my launches are going through just fine when I have @reportportal/agent-js-cypress denoted as my only reporter. However, when attempting to use cypress-multi-reporter, I run into an ECONNREFUSED issue (though the mochawesome report generates just fine).

```
Error: connect ECONNREFUSED [IP address]
    at [Project folder]/node_modules/@reportportal/client-javascript/lib/rest.js:31:23
```

My cypress.json has the following:
```
    "reporter": "cypress-multi-reporters",
    "reporterOptions": {
        "configFile": "reporter.json"
    }
```

And my reporter.json is as follows:
```
{
    "reporterEnabled": "@reportportal/agent-js-cypress, mochawesome",
    "agentJsCypressReporterOptions": {
        "endpoint": "http://localhost:8080/api/v1",
        "token": "35c84358-5bb2-419f-9bd7-3cafa424db74",
        "launch": "Cypress Test Run 2020.09.21",
        "project": "Pricing",
        "description": "Test run from [project name]",
        "isLaunchMergeRequired": true
    },
    "mochawesomeReporterOptions": {
        "reportDir": "cypress/reports/mocha",
        "quite": true,
        "overwrite": true,
        "html": false,
        "json": true
    }
}
```

Reporter options for the the Report Portal agent are identical to what I used as a solo reporter, where it was working. I know this is similar to an issue I've submitted in the past, but the error is new. What am I missing?

**Comment by evjlobanova** [comment]
@AmsterGet

**Comment by drewrichardson2** [comment]
Having this same issue. To me it looks like it is not referencing the config at all and instead loading default values. The ECONNREFUSED error I get notes that it tried connecting on `localhost:80` when I have it configured instead for `localhost:8080`. I get this to work just fine if I don't use the `cypress-multi-reporters` package.

**Comment by evjlobanova** [comment]
We will take a look at this issue this week

**Comment by drewrichardson2** [comment]
Hi guys, any updates on this?

**Comment by AmsterGet** [comment]
Hello everyone!
Sorry for delay.
Our team will investigate this issue next week.
Keep for updates!

**Comment by sharmadeepak43** [comment]
Hey Everyone,  I tried installing cypress-multi-reporters plugin and did the configurations which you mentioned in the issue -https://github.com/reportportal/agent-js-cypress/issues/46 but not able to generate even a single report. These are my configurations -
cypress.json -
"reporter": "cypress-multi-reporters",
      "reporterOptions": {
        "configFile": "reporter.json",
        "mochaFile": "cypress/results/results-[hash].xml"
      },
reporter.json -
{
  "reporterEnabled": "mocha-junit-reporter, agent-js-cypress",
  "mochawesomeReporterOptions": {
  "reportDir": "cypress/results",
  "overwrite": true,
  "html": false,
  "json": true
  },
  "agentJsCypressReporterOptions": {
  "endpoint": "endpoint",
  "token": "token",
  "launch": "name",
  "project": "name",
  "description": "description",
  "autoMerge": true,
  "isLaunchMergeRequired": true
  }
  }
But now i am not able to see the data in report portal as well the mochawesome report. Can anyone please take a look at the configuration please. I am able to generate the report with agent-js-cypress https://github.com/reportportal/agent-js-cypress  plugin, but it is limited to only one report generation. Thanks!!

**Comment by sharmadeepak43** [comment]
Hello Folks,
ay update on this issue ?
Regards,
Deepak

**Comment by stu85** [comment]
+1, also seeing the same issue when trying to use cypress-multi-reporters with "@reportportal/agent-js-cypress": "^5.0.1".

agent-js-cypress is working fine if it is configured as the only reporter, but when trying to use in conjunction with mochaesome or junit reporter I am seeing the same issue a described.

Fail to start launch Error: connect ECONNREFUSED 127.0.0.1:80

**Comment by drewrichardson2** [comment]
I fixed this issue by implementing my own config override file that runs for automation. Here's an example:

`const cypress = require('cypress');
const fs = require('fs');
const glob = require('glob');
const reportportal = require('@reportportal/agent-js-cypress')
const { mergeLaunches } = require('@reportportal/agent-js-cypress/lib/mergeLaunches');
 
const cypressConfigFile = 'cypress.json';
let config;
let data = fs.readFileSync(cypressConfigFile, 'utf8') 
config = JSON.parse(data)
config.reporterOptions.description = "A COMMIT SHA"
config.reporterOptions.token = process.env.RPP_TOKEN

cypress.run({reporterOptions : config.reporterOptions,
spec: "./cypress/integration/accounts/login.spec.js"}).then(
  () => {
    process.exit(0)
  },
);`

You can "intercept" the config by altering the `npm run` script and then making sure the values get set properly. You can see above I read in the file and then set what I need with `confi.reporterOptions.token = process.env.RPP_TOKEN`, for example.

**Comment by BibinQA** [comment]
I did something like this and both mochawesome and RP are working fine for me.
`{
  "reporterEnabled": "mochawesome,@reportportal/agent-js-cypress",
  "reporterOptions": {
    "reportDir": "cypress/test-results/reports/individual-reports",
    "overwrite": false,
    "reportFilename": "report",
    "html": false,
    "json": true,
    "endpoint": "http://reportportal.hci.aetna.com:8080/api/v1",
    "token": "cce6f7ad-b02d-4c21-a43f-a643275e7612",
    "launch": "Regression",
    "project": "personal",
    "description": "Cypress test",
    "autoMerge": true
  }
}`

**Comment by baradhiren** [comment]
This might have been resolved. But I was able to resolve this after three hours of trial and error by changing the reporterOption name:
Instead of "agentJsCypressReporterOptions" you should try "reportportalAgentJsCypressReporterOptions".
Have a look at the configuration part of mocha-multi-reporter: https://github.com/stanleyhlng/mocha-multi-reporters#configuring-reporters

**Comment by AmsterGet** [comment]
Hello everyone!
@baradhiren thanks for your comment!
We've added the cypress example for 'cypress-multi-reporters' configuration in our [examples](https://github.com/reportportal/examples-js/blob/master/example-cypress/cypress.json).
@BibinQA, @mleonard0826 this should fix the problem!
I'll close this issue, but feel free to ask any questions.

**Comment by BibinQA** [comment]
I am still not able to over ride reporter options. for eg : launch= Regression-dev, and the run never completes on report portal.

**Comment by akbarchandani** [comment]
> Hello everyone! @baradhiren thanks for your comment! We've added the cypress example for 'cypress-multi-reporters' configuration in our [examples](https://github.com/reportportal/examples-js/blob/master/example-cypress/cypress.json). @BibinQA, @mleonard0826 this should fix the problem! I'll close this issue, but feel free to ask any questions.

Hi @AmsterGet 

The cypress example with 'cypress-multi-reporters' still does not run, below is the erroe loc:

`Error: timeout of 30000ms exceeded
    at C:\Users\akbar.chandani\Documents\Akbar\Practice\VSCode\ReporPortal\examples-js\example-cypress\node_modules\@reportportal\client-javascript\lib\rest.js:36:23
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Fail to start launch Error: timeout of 30000ms exceeded
    at C:\Users\akbar.chandani\Documents\Akbar\Practice\VSCode\ReporPortal\examples-js\example-cypress\node_modules\@reportportal\client-javascript\lib\rest.js:36:23
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Fail to start suite Error: timeout of 30000ms exceeded
    at C:\Users\akbar.chandani\Documents\Akbar\Practice\VSCode\ReporPortal\examples-js\example-cypress\node_modules\@reportportal\client-javascript\lib\rest.js:36:23
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Fail to start test Error: timeout of 30000ms exceeded
    at C:\Users\akbar.chandani\Documents\Akbar\Practice\VSCode\ReporPortal\examples-js\example-cypress\node_modules\@reportportal\client-javascript\lib\rest.js:36:23
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Fail to start hook Error: timeout of 30000ms exceeded
    at C:\Users\akbar.chandani\Documents\Akbar\Practice\VSCode\ReporPortal\examples-js\example-cypress\node_modules\@reportportal\client-javascript\lib\rest.js:36:23
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Fail to start test Error: timeout of 30000ms exceeded
    at C:\Users\akbar.chandani\Documents\Akbar\Practice\VSCode\ReporPortal\examples-js\example-cypress\node_modules\@reportportal\client-javascript\lib\rest.js:36:23
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Fail to start hook Error: timeout of 30000ms exceeded
    at C:\Users\akbar.chandani\Documents\Akbar\Practice\VSCode\ReporPortal\examples-js\example-cypress\node_modules\@reportportal\client-javascript\lib\rest.js:36:23
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Fail to start test Error: timeout of 30000ms exceeded
    at C:\Users\akbar.chandani\Documents\Akbar\Practice\VSCode\ReporPortal\examples-js\example-cypress\node_modules\@reportportal\client-javascript\lib\rest.js:36:23
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Fail to start hook Error: timeout of 30000ms exceeded
    at C:\Users\akbar.chandani\Documents\Akbar\Practice\VSCode\ReporPortal\examples-js\example-cypress\node_modules\@reportportal\client-javascript\lib\rest.js:36:23
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Fail to finish test Error: timeout of 30000ms exceeded
    at C:\Users\akbar.chandani\Documents\Akbar\Practice\VSCode\ReporPortal\examples-js\example-cypress\node_modules\@reportportal\client-javascript\lib\rest.js:36:23
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Fail to finish hook Error: timeout of 30000ms exceeded
    at C:\Users\akbar.chandani\Documents\Akbar\Practice\VSCode\ReporPortal\examples-js\example-cypress\node_modules\@reportportal\client-javascript\lib\rest.js:36:23
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Fail to finish hook Error: timeout of 30000ms exceeded
    at C:\Users\akbar.chandani\Documents\Akbar\Practice\VSCode\ReporPortal\examples-js\example-cypress\node_modules\@reportportal\client-javascript\lib\rest.js:36:23
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Fail to finish test Error: timeout of 30000ms exceeded
    at C:\Users\akbar.chandani\Documents\Akbar\Practice\VSCode\ReporPortal\examples-js\example-cypress\node_modules\@reportportal\client-javascript\lib\rest.js:36:23
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Fail to finish hook Error: timeout of 30000ms exceeded
    at C:\Users\akbar.chandani\Documents\Akbar\Practice\VSCode\ReporPortal\examples-js\example-cypress\node_modules\@reportportal\client-javascript\lib\rest.js:36:23
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Fail to finish suite Error: timeout of 30000ms exceeded
    at C:\Users\akbar.chandani\Documents\Akbar\Practice\VSCode\ReporPortal\examples-js\example-cypress\node_modules\@reportportal\client-javascript\lib\rest.js:36:23
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Fail to finish test Error: timeout of 30000ms exceeded
    at C:\Users\akbar.chandani\Documents\Akbar\Practice\VSCode\ReporPortal\examples-js\example-cypress\node_modules\@reportportal\client-javascript\lib\rest.js:36:23
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:21124) UnhandledPromiseRejectionWarning: Error: timeout of 30000ms exceeded
    at C:\Users\akbar.chandani\Documents\Akbar\Practice\VSCode\ReporPortal\examples-js\example-cypress\node_modules\@reportportal\client-javascript\lib\rest.js:36:23
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:21124) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:21124) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:21124) UnhandledPromiseRejectionWarning: Error: timeout of 30000ms exceeded
    at C:\Users\akbar.chandani\Documents\Akbar\Practice\VSCode\ReporPortal\examples-js\example-cypress\node_modules\@reportportal\client-javascript\lib\rest.js:36:23
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:21124) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
(node:21124) UnhandledPromiseRejectionWarning: Error: timeout of 30000ms exceeded
    at C:\Users\akbar.chandani\Documents\Akbar\Practice\VSCode\ReporPortal\examples-js\example-cypress\node_modules\@reportportal\client-javascript\lib\rest.js:36:23
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:21124) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)
(node:21124) UnhandledPromiseRejectionWarning: Error: timeout of 30000ms exceeded
    at C:\Users\akbar.chandani\Documents\Akbar\Practice\VSCode\ReporPortal\examples-js\example-cypress\node_modules\@reportportal\client-javascript\lib\rest.js:36:23
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:21124) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 6)
(node:21124) UnhandledPromiseRejectionWarning: Error: timeout of 30000ms exceeded
    at C:\Users\akbar.chandani\Documents\Akbar\Practice\VSCode\ReporPortal\examples-js\example-cypress\node_modules\@reportportal\client-javascript\lib\rest.js:36:23
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:21124) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 7)
(node:21124) UnhandledPromiseRejectionWarning: Error: timeout of 30000ms exceeded
    at C:\Users\akbar.chandani\Documents\Akbar\Practice\VSCode\ReporPortal\examples-js\example-cypress\node_modules\@reportportal\client-javascript\lib\rest.js:36:23
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:21124) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 8)
Fail to start suite Error: timeout of 30000ms exceeded
    at C:\Users\akbar.chandani\Documents\Akbar\Practice\VSCode\ReporPortal\examples-js\example-cypress\node_modules\@reportportal\client-javascript\lib\rest.js:36:23
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Fail to start test Error: timeout of 30000ms exceeded
    at C:\Users\akbar.chandani\Documents\Akbar\Practice\VSCode\ReporPortal\examples-js\example-cypress\node_modules\@reportportal\client-javascript\lib\rest.js:36:23
    at processTicksAndRejections (internal/process/task_queues.js:93:5)`

**Comment by praveentata** [comment]
Hello All,

I had the same issue. I used the `cypress-multi-reporters` module where I have the same configuration but different `launch` [Launch Name] and it worked fine.

https://docs.cypress.io/guides/tooling/reporters#Multiple-reporters

I created another json file to configure report portal but with a different launch name.
`sanity-reporter-config.json`
```
{
  "reporterEnabled": "@reportportal/agent-js-cypress",
  "reporterOptions": {
    "endpoint": "http://<your-host>:8080/api/v1",
    "token": "<your-token>",
    "launch": "sanity_tests",
    "project": "cypress-ui",
    "description": "E2E tests",
    "autoMerge": true
  }
}
```

Then from command line:
`npx cypress run --reporter cypress-multi-reporters --reporter-options configFile=reporter-config.json --spec cypress/integration/spec.js --browser chrome`

I hope this helps.

**Comment by akbarchandani** [comment]
Thanks, I would give it a go.


Kind regards,


Akbar Chandani

________________________________

**Comment by viktorNedelko** [comment]
@praveentata Does this way support outputs to reportPortal and another reporter (e.g. mochawesome)? I tried your way, and the mochawesome config in cypress.json is naturally ignored when 
`npx cypress run --reporter cypress-multi-reporters --reporter-options configFile=sanity-reporter-config.json --spec cypress/integration/spec.js --browser chrome`
is launched from CLI, but I'd like one launch to have 2 report outputs.

**Comment by praveentata** [comment]
Hi @viktorNedelko ,

You can do something like this:

```{
    "reporterEnabled": "@reportportal/agent-js-cypress, mocha-junit-reporter, mochawesome",
    "reporterOptions": {
        "endpoint": "<your_endpoint>",
        "token": "<your_token>",
        "launch": "launch_name",
        "project": "cypress-ui",
        "description": "E2E tests",
        "autoMerge": true,
        "mochaFile": "cypress/results/results-[hash].xml",
        "reportDir": "cypress/results",
        "overwrite": false,
        "html": false,
        "json": true
    }
}```

Basically, what I understood is, if we want to use report portal along with other reporters, report portal properties should be the mentioned first. Everything else can follow in any sequence.

Now you run using this reporter file like: `npx cypress run --reporter cypress-multi-reporters --reporter-options configFile=sanity-reporter-config.json --spec cypress/integration/spec.js --browser chrome`

**Comment by viktorNedelko** [comment]
@praveentata Thank you! Your comment about the order really helped, that was the issue for me. Basically, it requires to be first and for me it only works when it's options are under `reporterOptions` property and not `agentJsCypressReporterOptions` or `reportportalAgentJsCypressReporterOptions`. 

I have to say tho, the mocha config did not work under that same object, so I corrected both the order and made separate config object too. 

So basically right now my `cypress.json` looks like this:
```
{
  ...
  "reporter": "cypress-multi-reporters",
  "reporterOptions": {
    "configFile": "reporterOpts.json"
  }
  ...
}
```

and my reporterOpts.json looks like this:
```
{
  "reporterEnabled": "@reportportal/agent-js-cypress, mochawesome",
  "reporterOptions": {
    "endpoint": "http://localhost:8080/api/v1",
    "token": "3b531798-87e6-49a8-a5fd-463b67d7bc6a",
    "launch": "Scheduler",
    "project": "superadmin_personal",
    "description": "E2E tests",
    "autoMerge": true
  },
  "mochawesomeReporterOptions": {
    "reportDir": "cypress/reports/mocha",
    "quiet": true,
    "overwrite": false,
    "html": false,
    "json": true
  }
}
```

Thanks again!
